# Generated by Django 5.1.5 on 2025-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessnumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='number',
            field=models.IntegerField(),
        ),
    ]
